### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by ingGhost** [trvswgnr/bs5-lightbox#20]
How to change background color to transaparent mate? i write this, but not work :(

```
.lightbox-carousel > .carousel-inner > .carousel-item > .ratio{
    background-color:#fff0;
  }
```

**Comment by trvswgnr** [comment]
@ingGhost the background is currently set in the style attribute, so to override, you will need to add `!important` like so:

```css
.lightbox-carousel > .carousel-inner > .carousel-item > .ratio{
    background-color:#fff0 !important;
}
```
